baseurl = "https://yuanj.top"
title = "yuanj's blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = ["hugo-search-fuse-js", "Mainroad"]
[Params.style.vars]
  highlightColor = "#a3b8cc"
[Name]
  name = "YuanJ"
  bio = "思绪来得快去得也快，偶尔会在这里停留"
  avatar = "images/avatar.png"

[Params]
  description = "思绪来得快去得也快，偶尔会在这里停留" # Description of your site
  opengraph = true
  readmore = true # Show "Read more" button in list if true
  pager = true
  post_meta = ["date"] # Order of post meta information
  mainSections = ["posts"]
  mathjax = true

[Params.logo]
  subtitle = "思绪来得快去得也快，偶尔会在这里停留" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = false # Configure layout for single pages
  widgets = ["misc", "taglist", "recent", "busuanzi"]

[Params.widgets]
  recent_num = 11
  tags_counter = true
  [[Params.widgets.misc.custom]]
    title = "README"
    url = "/readme"
[[Params.widgets.misc.custom]]
    title = "Projects"
    url = "/projects"
  [[Params.widgets.misc.custom]]
    title = "搜索"
    url = "/search"
  [[Params.widgets.misc.custom]]
    title = "友链"
    url = "/links"
  [[Params.widgets.misc.custom]]
    title = "用Email联系我"
    url = "/images/email.png"
  [[Params.widgets.misc.custom]]
    title = "GitHub"
    url = "https://github.com/yuanj82"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true