baseurl = "https://yuanj.top"
title = "yuanj's blog"
languageCode = "en-us"
paginate = "10"                          # 每页的文章数量
theme = ["cloud"]

[Params]
  post_meta = ["date"]
  mainSections = ["posts"]                           # 设定文章目录
  mathjax = true

[Params.topbar]
  subtitle = "思绪来得快去得也快，偶尔会在这里停留"     # 顶栏副标题

[Params.sidebar]
  home = "right"                                         # 侧栏的位置
  widgets = ["misc", "taglist", "recent","busuanzi"]     # 侧栏要显示的项目

[Params.widgets]
  recent_num = 11                 # 设定RECENT POSTS栏的文章数量
  tags_counter = true             # 是否显示tags的文章数量
  [[Params.widgets.misc.custom]]  # MISC栏可以定义多个页面或url，页面应新建于content目录下
    title = "README"
    url = "/readme"
  [[Params.widgets.misc.custom]]
    title = "Links"
    url = "/links"
  [[Params.widgets.misc.custom]]
    title = "Publications"
    url = "/publications"
  [[Params.widgets.misc.custom]]
    title = "E-mail"
    url = "/images/email.png"
  [[Params.widgets.misc.custom]]
    title = "GitHub"
    url = "https://github.com/yuanj82"
  [[Params.widgets.misc.custom]]
    title = "RSS"
    url = "/index.xml"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true